// frontend-react/src/pages/Companies.tsx
import { useQuery } from '@tanstack/react-query';
import { companyService } from '../services/api';
import type { Company } from '../types';

export default function Companies() {
    const { data: companies, isLoading, isError } = useQuery<Company[]>({
        queryKey: ['companies'],
        queryFn: companyService.findAll,
    });

    if (isLoading) return <p className="text-gray-400">Loading...</p>;
    if (isError) return <p className="text-red-400">Error loading companies.</p>;

    return (
        <div>
            <h2 className="text-2xl font-bold mb-6">Companies</h2>

            {companies?.length === 0 ? (
                <p className="text-gray-400">No companies yet.</p>
            ) : (
                <table className="w-full text-sm">
                    <thead>
                    <tr className="text-left text-gray-400 border-b border-gray-800">
                        <th className="pb-3">Name</th>
                        <th className="pb-3">Tax Number</th>
                        <th className="pb-3">Created At</th>
                    </tr>
                    </thead>
                    <tbody>
                    {companies?.map((company) => (
                        <tr key={company.id} className="border-b border-gray-800 hover:bg-gray-900">
                            <td className="py-3">{company.name}</td>
                            <td className="py-3">{company.taxNumber}</td>
                            <td className="py-3">{new Date(company.createdAt).toLocaleDateString()}</td>
                        </tr>
                    ))}
                    </tbody>
                </table>
            )}
        </div>
    );
}

// frontend/src/app/pages/companies/companies.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { CompanyService } from '../../services';
import { Company } from '../../models';

@Component({
  selector: 'app-companies',
  standalone: true,
  imports: [DatePipe],
  template: `
    <div>
      <div class="flex items-center justify-between mb-6">
        <div>
          <h2 class="text-2xl font-bold text-white mb-1">Companies</h2>
          <p class="text-gray-400 text-sm">Tenant companies registered in the fleet platform</p>
        </div>
        <button
          (click)="loadCompanies()"
          class="px-4 py-2 bg-gray-800 hover:bg-gray-700 text-gray-200 text-sm rounded-lg border border-gray-700 transition-colors"
        >
          ↻ Refresh
        </button>
      </div>

      <!-- Loading State -->
      @if (isLoading()) {
        <div class="space-y-3 animate-pulse">
          <div class="h-10 bg-gray-900 border border-gray-800 rounded-lg"></div>
          <div class="h-14 bg-gray-900/60 border border-gray-800 rounded-lg"></div>
          <div class="h-14 bg-gray-900/60 border border-gray-800 rounded-lg"></div>
        </div>
      }

      <!-- Error State -->
      @if (errorMessage()) {
        <div class="bg-red-950/60 border border-red-800 text-red-200 px-4 py-3 rounded-xl mb-6 flex items-center justify-between">
          <p class="text-sm">{{ errorMessage() }}</p>
          <button (click)="loadCompanies()" class="text-xs bg-red-900 hover:bg-red-800 px-3 py-1 rounded">
            Retry
          </button>
        </div>
      }

      <!-- Table View -->
      @if (!isLoading() && !errorMessage()) {
        @if (companies().length === 0) {
          <div class="bg-gray-900 border border-gray-800 rounded-xl p-12 text-center">
            <p class="text-gray-400 text-sm">No companies registered yet.</p>
          </div>
        } @else {
          <div class="overflow-x-auto rounded-xl border border-gray-800 bg-gray-900/50">
            <table class="w-full text-sm text-left">
              <thead>
                <tr class="text-gray-400 border-b border-gray-800 bg-gray-900/80">
                  <th class="px-6 py-4 font-medium">Name</th>
                  <th class="px-6 py-4 font-medium">Tax Number (NIF)</th>
                  <th class="px-6 py-4 font-medium">Created At</th>
                </tr>
              </thead>
              <tbody class="divide-y divide-gray-800">
                @for (company of companies(); track company.id) {
                  <tr class="hover:bg-gray-800/50 transition-colors">
                    <td class="px-6 py-4 font-medium text-white">{{ company.name }}</td>
                    <td class="px-6 py-4 font-mono text-gray-300">{{ company.taxNumber }}</td>
                    <td class="px-6 py-4 text-gray-400">
                      {{ company.createdAt | date: 'mediumDate' }}
                    </td>
                  </tr>
                }
              </tbody>
            </table>
          </div>
        }
      }
    </div>
  `
})
export class CompaniesComponent implements OnInit {
  private readonly companyService = inject(CompanyService);

  readonly companies = signal<Company[]>([]);
  readonly isLoading = signal<boolean>(true);
  readonly errorMessage = signal<string | null>(null);

  ngOnInit(): void {
    this.loadCompanies();
  }

  loadCompanies(): void {
    this.isLoading.set(true);
    this.errorMessage.set(null);

    this.companyService.findAll().subscribe({
      next: (data) => {
        this.companies.set(data || []);
        this.isLoading.set(false);
      },
      error: () => {
        this.errorMessage.set('Error loading companies from API.');
        this.isLoading.set(false);
      }
    });
  }
}
